nox-review: Fix --keep-going
Currently e.g. `nox-review --keep-going wip --against HEAD^` fails
because extra-args is being set to `[["--keep-going"]]`, that is a list
of list containing a string. This crashes nox later on:

  File "/nix/store/82f7gbp1byi5qp78rjrapzl7z97whjkp-nox-0.0.6/lib/python3.6/site-packages/nox/review.py", line 38, in build_in_path
    click.echo('Invoking {}'.format(' '.join(command)))
TypeError: sequence item 1: expected str instance, list found

Remove the extra list to fix the crash.