nixpkgs_repo: Use 'git checkout -f'
Because if a previous 'nox-review pr' run leaves the ~/.nox/nixpkgs repo
in a merge conflict resolution state, then any further runs of
nox-review will fail since 'git checkout' gives up:

==> Merging PR into base
pkgs/development/haskell-modules/configuration-common.nix: needs merge
error: you need to resolve your current index first

Using '-f' to force the checkout fixes this.